// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (account_id, name)
VALUES (
	$1,
	$2
) RETURNING id, account_id, name, xp, gold, deaths, created_at, xp_updated_at, level
`

type CreateCharacterParams struct {
	AccountID uuid.UUID
	Name      string
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter, arg.AccountID, arg.Name)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Xp,
		&i.Gold,
		&i.Deaths,
		&i.CreatedAt,
		&i.XpUpdatedAt,
		&i.Level,
	)
	return i, err
}

const getCharacterByAccount = `-- name: GetCharacterByAccount :one
SELECT id, account_id, name, xp, gold, deaths, created_at, xp_updated_at, level FROM characters WHERE account_id = $1
`

func (q *Queries) GetCharacterByAccount(ctx context.Context, accountID uuid.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterByAccount, accountID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Xp,
		&i.Gold,
		&i.Deaths,
		&i.CreatedAt,
		&i.XpUpdatedAt,
		&i.Level,
	)
	return i, err
}
