// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const applyStats = `-- name: ApplyStats :one
UPDATE characters
	SET xp = xp + $1,
	gold = gold + $2,
	deaths = deaths + $3
WHERE id = $4
RETURNING level
`

type ApplyStatsParams struct {
	XpDelta     int64
	GoldDelta   int64
	DeathsDelta int32
	CharacterID uuid.UUID
}

func (q *Queries) ApplyStats(ctx context.Context, arg ApplyStatsParams) (int32, error) {
	row := q.db.QueryRow(ctx, applyStats,
		arg.XpDelta,
		arg.GoldDelta,
		arg.DeathsDelta,
		arg.CharacterID,
	)
	var level int32
	err := row.Scan(&level)
	return level, err
}

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (account_id, name)
VALUES (
	$1,
	$2
) RETURNING id, account_id, name, xp, gold, deaths, created_at, xp_updated_at, level
`

type CreateCharacterParams struct {
	AccountID uuid.UUID
	Name      string
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter, arg.AccountID, arg.Name)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Xp,
		&i.Gold,
		&i.Deaths,
		&i.CreatedAt,
		&i.XpUpdatedAt,
		&i.Level,
	)
	return i, err
}

const getCharacterByAccount = `-- name: GetCharacterByAccount :one
SELECT id, account_id, name, xp, gold, deaths, created_at, xp_updated_at, level FROM characters WHERE account_id = $1
`

func (q *Queries) GetCharacterByAccount(ctx context.Context, accountID uuid.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterByAccount, accountID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Xp,
		&i.Gold,
		&i.Deaths,
		&i.CreatedAt,
		&i.XpUpdatedAt,
		&i.Level,
	)
	return i, err
}
