// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboard.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const leaderboardAfter = `-- name: LeaderboardAfter :many
SELECT username, name, level, xp, xp_updated_at, id FROM leaderboard
WHERE xp <= $1
	AND (
		xp < $1
		OR xp_updated_at > $2
		OR (xp_updated_at = $2 AND id > $3))
ORDER BY xp DESC, xp_updated_at ASC, id
LIMIT $4
`

type LeaderboardAfterParams struct {
	Xp          int64
	XpUpdatedAt time.Time
	ID          uuid.UUID
	PageSize    int32
}

func (q *Queries) LeaderboardAfter(ctx context.Context, arg LeaderboardAfterParams) ([]Leaderboard, error) {
	rows, err := q.db.Query(ctx, leaderboardAfter,
		arg.Xp,
		arg.XpUpdatedAt,
		arg.ID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Leaderboard
	for rows.Next() {
		var i Leaderboard
		if err := rows.Scan(
			&i.Username,
			&i.Name,
			&i.Level,
			&i.Xp,
			&i.XpUpdatedAt,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leaderboardTop = `-- name: LeaderboardTop :many
SELECT username, name, level, xp, xp_updated_at, id FROM leaderboard ORDER BY xp DESC, xp_updated_at ASC, id LIMIT $1
`

func (q *Queries) LeaderboardTop(ctx context.Context, pageSize int32) ([]Leaderboard, error) {
	rows, err := q.db.Query(ctx, leaderboardTop, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Leaderboard
	for rows.Next() {
		var i Leaderboard
		if err := rows.Scan(
			&i.Username,
			&i.Name,
			&i.Level,
			&i.Xp,
			&i.XpUpdatedAt,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
