// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	CreatedAt    time.Time
}

type Character struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Name        string
	Level       int32
	Xp          int64
	Gold        int64
	Deaths      int32
	CreatedAt   time.Time
	XpUpdatedAt time.Time
}

type Leaderboard struct {
	Username    string
	Name        string
	Level       int32
	Xp          int64
	XpUpdatedAt time.Time
	ID          uuid.UUID
}
